### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Vitor-Bukovitz** [GustavoMartinsDosSantos/Chat-ReactNative#1]
**Hello. It's not working.**

**Comment by GustavoMartinsDosSantos** [comment]
Oh, hello Vitor, you again...
Please, could you send a print from the error messages?

Regards,

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
**_This is the error that i'm getting:_**

![image](https://user-images.githubusercontent.com/24995642/83446668-73b1d180-a425-11ea-8852-11fbf9ccaaba.png)

**Thanks!!**

**Comment by GustavoMartinsDosSantos** [comment]
Well Victor, i think i didnt even need to answer this but, you must update your react native

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
Error after updating my react-native:

![image](https://user-images.githubusercontent.com/24995642/83530732-84fceb80-a4c2-11ea-843d-ed2d93d09ec6.png)

**Comment by GustavoMartinsDosSantos** [comment]
Vitor... are you acessing my Project from your enterprise computer??? Thats not acceptable my friend. Oh, and i am pretty sure you havent updated your react native properly. Please, uninstall any dependencies and any other file, and try downloading it all again.

Regards,

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
Hey @GustavoMartinsDosSantos !
How are you?

just tried that my friend and i'm still stuck with this damn issue.

this is the error now:

![image](https://user-images.githubusercontent.com/24995642/83558896-12a00180-a4ea-11ea-9f57-018f312b1100.png)

**Comment by GustavoMartinsDosSantos** [comment]
Vitor, hello buddy.
Enter in the project folder, and the type on your prompt: "cd android". That wil take you to the android folder. Once you are inside the android folder, type in your prompt: "gradlew assembleRelease" just try it my long date friend. Lets see what happens.

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
@GustavoMartinsDosSantos , hello mate.

I tried to run the command and this is what i got:

![62615828-b13fee00-b92b-11e9-9b3a-8cf0b8fc2308](https://user-images.githubusercontent.com
/24995642/83684757-ef468680-a5bd-11ea-85ca-9333b6a39edd.png)


Still not working.

**Comment by GustavoMartinsDosSantos** [comment]
Oh Vitor, its the same message you posted on the calculator... Please, go there to see the solution.

Att;
Gustavo Martins dos Santos.
47 9 97311529

________________________________

**Comment by Vitor-Bukovitz** [comment]
FRIEND YOU ASKED ME TO DO THE SAME THING ON THE OTHER ISSUE. I JUST DID THE SAME AND SENT THE SAME ANSWER.















**_REGARDS_**.

**Comment by GustavoMartinsDosSantos** [comment]
Ohh, seems that we have a tough one here uh?
So let me explain one thing here sir: YOUR PROBLEMS ARE NOT MINE. DONT EXPECT THAT I WILL BE RESOLVING THEN. SO GET UP YOUR PHAT ASS FROM YOUR CHAIR, DO SOMETHING, AND STOP BOTHERING ME.

Att;
Gustavo Martins dos Santos.
47 9 97311529

**Comment by Vitor-Bukovitz** [comment]
**useless.**
